spring.application.name=open-telemetry-example

# Tracing only ? disable logs and metrics export to Jaeger
otel.logs.exporter=none
otel.metrics.exporter=none
otel.exporter.otlp.endpoint=http://localhost:4318
management.tracing.sampling.probability=1.0

otel.instrumentation.logback-appender.enabled=false

pulsar.service-url=pulsar://localhost:6650

#spring.docker.compose.readiness.timeout=5m
spring.docker.compose.readiness.wait=never


logging.pattern.level=%5p [${spring.application.name},%X{traceId},%X{spanId}]


spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-only
